### PR TITLE
Upgrade ipfs and orbit-db deps

### PR DESCRIPTION
**Pull request by tabcat**

### CODE REVIEW

**Comment by aphelionz** [comment]
Judging from the test changes it seems we do _not_ need a major version bump here since the core APIs didn't change. Am I reading those right?

**Comment by tabcat** [comment]
yes its just CID thats been changed which isnt really us

**Comment by aphelionz** [comment]
Approving despite browser tests

**Comment by tabcat** [comment]
this should pass but needs to be cleaned up before merging @aphelionz

**Review by aphelionz — APPROVED** [review]

**Pull request merged**
