### PR TITLE
Run tests with go-ipfs

### PR DESCRIPTION
**Pull request by haadcode**
This PR will add support running tests with go-ipfs.

Changes:
- Add go-ipfs and ipfsd-ctl as dev dependencies
- Remove obsolete "coverage" script from package.json
- Copy go-ipfs test utility functions from orbit-db
- Use datastore-level in test js-ipfs instances
- Refactor tests to use both ipfs implementations
- Add instructions to README

### CODE REVIEW

**Comment by haadcode** [comment]
I believe we're hitting the same bug with go-ipfs 0.4.17 (latest) as in https://github.com/orbitdb/orbit-db/pull/417 and the replication tests some times fail (in short: peers don't connect on pubsub level even though they're connected on peer-level, bug reported here https://github.com/libp2p/go-floodsub/issues/93).

With 0.4.10 the tests seem to run successfully.

**Comment by haadcode** [comment]
This seems to be fixed now with go-ipfs 0.4.17 (latest). The fix was to *not* connect peers manually before starting the tests and let go-ipfs handle it through peer discovery.

**Comment by shamb0t** [comment]
LGTM :tada: :smiley:

**Comment by haadcode** [comment]
Thanks 👍

**Pull request merged**
