### PR TITLE
chore(dependencies): Applying Alan Shaw's js-ipfs 0.33.0 upgrades

### LINKED ISSUE #183: preparations for js-ipfs 0.33
👋 I upgraded `ipfs` to `0.33.0-rc.4`, `datastore-level` to `^0.9.0`, `ipfs-repo` to `^0.24.0` and ran the tests and they all passed \o/

https://github.com/ipfs/js-ipfs/issues/1635

### PR DESCRIPTION
**Pull request by aphelionz**
Maintenance PR for applying @alanshaw's changes as described here https://github.com/orbitdb/ipfs-log/issues/183

## Updates:
* `ipfs` to `~0.33.0`
* `datastore-level` to `^0.9.0`
* `ipfs-repo` to `^0.24.0` 

## Next Steps (after this PR)

- [x] Run `npm audit fix` and compare results

Resolves #183

### CODE REVIEW

**Comment by aphelionz** [comment]
@RichardLitt Check one more time.

* Updated the package version to `4.2.0`
* Ran `npm build`
* Ran `npm build:examples`

**Comment by haadcode** [comment]
@aphelionz thank you, looking good 👍

However, we shouldn't update the package version here as we would do that only upon on a npm new release, from master. That is, the package version gets updated manually as part of the npm release process and shouldn't be changed in PRs.

**Comment by aphelionz** [comment]
@haadcode roger that. I'll change it back

**Comment by aphelionz** [comment]
@haadcode all set!

**Comment by haadcode** [comment]
LGTM 👍

**Comment by RichardLitt** [comment]
@haadcode Would Greenkeeper help here?

**Comment by haadcode** [comment]
@RichardLitt we had Greenkeeper for all the ecosystem modules in the past. We turned it off because, well, it wasn't so helpful (more noise than signal). This was couple of years ago, they have prolly improved on it and generally if people feel like it can be helpful, we can definitely start using it again 👍

**Comment by RichardLitt** [comment]
Ah, yeah, I remember that. I think it's a bit better now - but keeping the noise down is hard. Might make sense to jerry-rig something similar that only updates once every three months. Would that be useful?

**Pull request merged**
