### PR TITLE
Feat/ipfs dag

### PR DESCRIPTION
**Pull request by shamb0t**
This PR updates ipfs.object calls to use ipfs.dag API

### CODE REVIEW

**Comment by shamb0t** [comment]
Some concerns discussed in #200

**Comment by haadcode** [comment]
Looking really good @shamb0t! 👍 Would it be possible to split this PR into two: Feat/ipfs-dag and "Update webpack and babel" (which only upgrades the deps as you've done here)?

**Comment by satazor** [comment]
Also regarding this, we can either use `cbor` or `protobuf`. `cbor` is easier to do because we just need to write a json object like so:

```js
ipfs.dag.put({
   ...e,
   next: e.next.map((cid) => ({ '/': cid })
});
```

While using pb you have to construct the dagNode manually using `https://github.com/ipld/js-ipld-dag-pb`. Protobufs should be faster than cbor but I'm not really sure, perhaps @vmx could advise us here.

**Comment by haadcode** [comment]
@satazor would you want to PR the above "use IPLD links"? We define the shape of the entry objects here: https://github.com/orbitdb/ipfs-log/blob/master/src/entry.js#L30.

**Comment by vmx** [comment]
> perhaps @vmx could advise us here.

My advise is to use dag-cbor and not using dag-pb. I hope that one day dag-pb will not be used anymore. If things don't work/are slow it should be fixed, rather then having someone using dag-pb.

**Comment by satazor** [comment]
@haadcode Yep, and as per @vmx advice we should use cbor. I will be giving a workshop in a few hours so it’s difficult me for me to focus on this, but I already had everything using ipld links using cbor. I can either open a new PR with they or let @shamb0t change this PR instead.

**Comment by haadcode** [comment]
@satazor if you have the code ready, please do PR it and whoever can then cherry pick the approriate commits/changes to this PR 👍

**Comment by shamb0t** [comment]
Thanks for the info here guys! @satazor Feel free to open a new PR with cbor ipld links whenever you're ready and we can work from there

**Comment by satazor** [comment]
Alright, I will do that either tonight or earlier in the morning. @shamb0t feel free to take on this if you want and have the time!

**Comment by shamb0t** [comment]
closing in favour of #213

**Pull request closed without merging**
