### PR TITLE
Allow to specify a timeout for each function that performs reads.

### LINKED ISSUE #199: Ensure that we have timeouts in place when reading/writing nodes in IPFS
From: https://github.com/ipfs/dynamic-data-and-capabilities/issues/50

Ensure that we have timeouts in place when reading/writing nodes in IPFS

### PR DESCRIPTION
**Pull request by satazor**
## Description (Required)

Allow to specify the maximum amount of time to wait for a fetch/read operation from IPFS. This is a new feature.

## Other changes (e.g. bug fixes, UI tweaks, refactors)

None.

## TODO

- [ ] Add unit test
- [ ] Add documentation

Resolves #199

### CODE REVIEW

**Comment by aphelionz** [comment]
@satazor My PR #220 has been merged. You should be able to work your timeouts into the destructure options object now.

**Comment by satazor** [comment]
@aphelionz could you take on this PR? I will be focusing my attention in a decentralized identity solution for the DDCWG, called IDM, so my time will be limited.

**Comment by aphelionz** [comment]
Possibly, I'll let you know.

**Comment by aphelionz** [comment]
Closing this as it has unfortunately become stale and i obviously haven't been able to look at it :(

We can re-open if this is still something people are interested in.

**Pull request closed without merging**
