### PR TITLE
Fix missing identity in entry.fromMultihash

### PR DESCRIPTION
**Pull request by shamb0t**
This PR fixes the missing identity field in Entry.fromMulthash 
Adds check for equality in fromMultihash test

### CODE REVIEW

**Comment by haadcode** [comment]
Looks good but test are erroring with: "/home/ubuntu/orbitdb/ipfs-log/test/entry.spec.js
  201:9  error  'assert.deepEqual' was deprecated since v10.0.0. Use 'assert.deepStrictEqual' or 'assert.strict.deepEqual' instead  node/no-deprecated-api"

**Comment by haadcode** [comment]
Not tests, linting

**Comment by shamb0t** [comment]
Yea its the linter, but deepStrictEqual is failing:
``` 
    AssertionError [ERR_ASSERTION]: { hash: 'QmVDZw6kFVnfBur62cdjJvypP7E8xuJ9mGb2fScBapdqe9',
  id: 'A',
  payload: 'hello again',
  next: [ 'QmVPLSEsaiypMFtaZEPwGp deepStrictEqual { hash: 'QmVDZw6kFVnfBur62cdjJvypP7E8xuJ9mGb2fScBapdqe9',
  id: 'A',
  payload: 'hello again',
  next: [ 'QmVPLSEsaiypMFtaZEPwGp
      + expected - actual

```
I think the way deep comparisons are done has changed?

**Comment by haadcode** [comment]
"Use 'assert.deepStrictEqual' or 'assert.strict.deepEqual' instead node/no-deprecated-api"

I think this was introduced through the linting rules (which is fine I think since nodejs 10 is soon LTS and we should officially support/use it).

**Comment by shamb0t** [comment]
Good to merge :+1:

**Pull request merged**
